# spring Configuration
spring:
   application:
      name: mysite
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
   
   # mvc
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
#      view:
#         prefix: /WEB-INF/views/
#         suffix: .jsp
#         exposeContextBeansAsAttributes: true
   web:
      resources:
         static-locations: classpath:/assets/, file:/users/kdj/mysite-uploads/upload-images/
   
   #multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
         
   # message resource(internationalization, i18n)
   messages:
      always-use-message-format: true
      basenames: web/messages/messages
      encoding: utf-8
   
   # datasource
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.0.211:3307/webdb?charset=utf8
      username: webdb
      password: webdb
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
    
   # aop
   aop:
      auto: true
      proxy-target-class: true
     
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

# Server
server:
   port: 8088
   servlet:
      context-path: /mysite06
      encoding:
         charset: utf-8
         enabled: true